flowchart LR
    J[Jugadores]
    G[Galaxias]
    P[Planetas]
    L[Lunas]
    R[Recursos]
    N[Naves]
    E[Edificios]
    A[Armamentos]

    RG{contiene}
    RJ{posee}
    RL{tiene}
    RR{tiene}
    RN{alberga}
    RE{construye}
    RA{instala}

    G -- "1" --> RG
    RG -- "N" --> P

    J -- "1" --> RJ
    RJ -- "N" --> P

    P -- "1" --> RL
    RL -- "N" --> L

    P -- "(n,m)" --> RR
    RR -- "(n,m)" --> R

    P -- "(n,m)" --> RN
    RN -- "(n,m)" --> N

    P -- "(n,m)" --> RE
    RE -- "(n,m)" --> E

    P -- "(n,m)" --> RA
    RA -- "(n,m)" --> A
