flowchart TB
    J["Jugadores
PK <u>id</u>
username
email
password
fecha_registro"]

    G["Galaxias
PK <u>id</u>
nombre
sector"]

    P["Planetas
PK <u>id</u>
nombre
coordenadaX
coordenadaY
superficie
FK id_galaxia -> <u>Galaxias.id</u>
FK jugador_id -> <u>Jugadores.id</u>"]

    L["Lunas
PK <u>id</u>
nombre
superficie
FK planeta_id -> <u>Planetas.id</u>"]

    R["Recursos
PK <u>id</u>
nombre"]

    N["Naves
PK <u>id</u>
nombre
costo_metal
costo_cristal
costo_energia"]

    E["Edificios
PK <u>id</u>
nombre
costo_metal
costo_cristal
costo_energia"]

    A["Armamentos
PK <u>id</u>
nombre
costo_metal
costo_cristal
costo_energia"]

    PR["Planetas_Recursos
PK/FK <u>planeta_id</u> -> <u>Planetas.id</u>
PK/FK <u>recurso_id</u> -> <u>Recursos.id</u>
cantidad"]

    PN["Planetas_Naves
PK/FK <u>planeta_id</u> -> <u>Planetas.id</u>
PK/FK <u>nave_id</u> -> <u>Naves.id</u>
cantidad"]

    PE["Planetas_Edificios
PK/FK <u>planeta_id</u> -> <u>Planetas.id</u>
PK/FK <u>edificio_id</u> -> <u>Edificios.id</u>
nivel"]

    PA["Planetas_Armamentos
PK/FK <u>planeta_id</u> -> <u>Planetas.id</u>
PK/FK <u>armamento_id</u> -> <u>Armamentos.id</u>
cantidad"]

    G --> P
    J --> P
    P --> L

    P --> PR
    R --> PR

    P --> PN
    N --> PN

    P --> PE
    E --> PE

    P --> PA
    A --> PA
